### ISSUE TITLE
Multiple errors given by the new VirSorter script

### ISSUE THREAD

**Issue by genomics-pixel** [simroux/VirSorter#52] opened 2019-09-30 12:07 UTC
Dear Simon,

Thank you for your generous help with VirSorter earlier.

I am sorry to bring up another issue, but when I have 
tried the new VirSorter script (i.e. the one made available after issue#48)
on my larger set of data,  it gave me multiple errors.
[virsorter_err_log_for_simon.txt](https://github.com/simroux/VirSorter/files/3670898/virsorter_err_log_for_simon.txt) 
(The above file contains all of the errors that were given in different VirSorter analyses)

From the list of errors, it seems that there are mainly two types of issue.
 1. Failure of "cat" command to find "r_2/Contigs_prots_vs_New_unclustered.tab"
 2. Problem with usage of uninitialized value 

If you could please take time to look at this that would fantastic.

Sincerely,
genomics-pixel

**Comment by simroux** [comment] 2019-09-30 15:59
Hi,
Thanks for reporting these. The good news is that none of these are real errors, but these are warnings. The "uninitialized value" ones should have been fixed in the last release  (Sep 16). The "Failure of "cat" command to find "r_2/Contigs_prots_vs_New_unclustered.tab"" is most likely a warning as well because it only occurs in "r_2", not in the previous rounds. I just pushed a new version where this case is anticipated and should not print the warning anymore.

Let me know if you see anything else !
Best,
Simon

**Comment by genomics-pixel** [comment] 2019-10-01 01:33
Dear Simon,

Great to know that these messages are just warnings and not errors!
Also many thanks for putting up a new version of VirSorter!!

I will have the newest version of your VirSorter installed in our computer cluster and
re-run the analysis!

Again thanks for your fantastic help.

Sincerely,
genomics-pixel

**Comment by genomics-pixel** [comment] 2019-10-03 01:57
Dear Simon, 

I tried the new VirSorter script and found that there were still some errors.
[List_of_errors_2019_10_03.txt](https://github.com/simroux/VirSorter/files/3684138/List_of_errors_2019_10_03.txt)

The errors were related with "Use of uninitialized value".

If you could tell me whether this effects the results or not that would be great.

Sincerely,
genomics-pixel

**Comment by simroux** [comment] 2019-10-03 21:44
Hi,
So these are all warnings, and won't impact the results at all. Which means, hopefully, you should be all good from now on :-)

**Comment by genomics-pixel** [comment] 2019-10-07 04:46
Dear Simon,

It's great to know that these messages are just warnings and should not affect the results!

Currently, I am looking through VirSorter results and noticed that 
there are still some overlapping viral regions.
(VirSorter was run with version eadcee5 (i.e. the newest version )of wrapper_phage_contigs_sorter_iPlant.pl)

However, these overlapping viral regions are unlike the ones I have reported
in previous issues **as they do not have identical start or end positions**. 

Ex.)
>\>VIRSorter_k251_76503_flag_1_multi_82_0000_len_18387_SAMPLE10_**gene_6_gene_17**-**4753-17933**-cat_4
>- Start coordinate 4,753 bp
>- End coordinate 17,933 bp

>\>VIRSorter_k251_76503_flag_1_multi_82_0000_len_18387_SAMPLE10_**gene_5_gene_15**-**3787-14472**-cat_5
>- Start coordinate 3,787 bp
>- End coordinate 14,472 bp


If I understand your paper correctly, VirSorter uses sliding windows to 
identify regions enriched with viral signatures. 

Therefor, my guess is **that above such cases are intended to be detected by VirSorter
and thus should not be a problem**, but I am not certain.

I am sorry to ask you so many questions, but if you could please enlighten me
on this matter I would appreciate it very much

Thank you in advance.

Sincerely,
genomics-pixel

**Comment by simroux** [comment] 2019-10-07 13:46
Hi,

Yes, it is a known VirSorter limitation that these kind of overlapping prophage predictions exist. So it is "working as intended", in the sense that these are problematic situations that VirSorter can't automatically solve by itself.

Best,
Simon

**Comment by genomics-pixel** [comment] 2019-10-08 13:45
Dear Simon, 

Many thanks for your helpful reply!
I now understand that in some rare situations there will be overlapping viral region predicted.

Would it make sense to take such cases where there are overlaps in predicted viral region as it is and regard both overlapping regions as possible prophage regions?

Sincerely,
genomics-pixel

**Comment by simroux** [comment] 2019-10-08 14:08
In my opinion yes, it shouldn't impact thing too much. Another option is to only select one of the two when prophages are overlapping (by manually looking at the sequence annotation).

**Comment by genomics-pixel** [comment] 2019-10-09 01:26
Dear Simon,

Thank you for your quick reply and teaching me how I can handle situations where predicted viral regions overlap each other. Since both ways of handling overlaps are fine, I think I will go with regarding both overlapping regions as possible prophage regions.

VirSorter is a really fantastic virus prediction tool and I greatly appreciate your generous help in using it. Again many thanks!

Sincerely,
genomics-pixel

**Closed** 2019-10-15 11:30 UTC
